/// Map a Gen IV national Pokédex species ID (1–493) to its lowercase species name.
///
/// Names match the convention used throughout the overlay (e.g. `"bulbasaur"`,
/// `"mr-mime"`, `"ho-oh"`), which is also the filename stem expected for sprites.
///
/// Returns `None` for ID 0 or any ID above 493.
pub fn name_from_id(id: u16) -> Option<&'static str> {
    SPECIES.get(id as usize).copied().flatten()
}

/// Index 0 is unused (no species has ID 0). Indices 1–493 are the national dex
/// numbers for Generation I through IV, sourced from PokéAPI.
static SPECIES: &[Option<&str>] = &[
    None,               // 0 – unused
    Some("bulbasaur"),  // 1
    Some("ivysaur"),    // 2
    Some("venusaur"),   // 3
    Some("charmander"), // 4
    Some("charmeleon"), // 5
    Some("charizard"),  // 6
    Some("squirtle"),   // 7
    Some("wartortle"),  // 8
    Some("blastoise"),  // 9
    Some("caterpie"),   // 10
    Some("metapod"),    // 11
    Some("butterfree"), // 12
    Some("weedle"),     // 13
    Some("kakuna"),     // 14
    Some("beedrill"),   // 15
    Some("pidgey"),     // 16
    Some("pidgeotto"),  // 17
    Some("pidgeot"),    // 18
    Some("rattata"),    // 19
    Some("raticate"),   // 20
    Some("spearow"),    // 21
    Some("fearow"),     // 22
    Some("ekans"),      // 23
    Some("arbok"),      // 24
    Some("pikachu"),    // 25
    Some("raichu"),     // 26
    Some("sandshrew"),  // 27
    Some("sandslash"),  // 28
    Some("nidoranf"),   // 29
    Some("nidorina"),   // 30
    Some("nidoqueen"),  // 31
    Some("nidoranm"),   // 32
    Some("nidorino"),   // 33
    Some("nidoking"),   // 34
    Some("clefairy"),   // 35
    Some("clefable"),   // 36
    Some("vulpix"),     // 37
    Some("ninetales"),  // 38
    Some("jigglypuff"), // 39
    Some("wigglytuff"), // 40
    Some("zubat"),      // 41
    Some("golbat"),     // 42
    Some("oddish"),     // 43
    Some("gloom"),      // 44
    Some("vileplume"),  // 45
    Some("paras"),      // 46
    Some("parasect"),   // 47
    Some("venonat"),    // 48
    Some("venomoth"),   // 49
    Some("diglett"),    // 50
    Some("dugtrio"),    // 51
    Some("meowth"),     // 52
    Some("persian"),    // 53
    Some("psyduck"),    // 54
    Some("golduck"),    // 55
    Some("mankey"),     // 56
    Some("primeape"),   // 57
    Some("growlithe"),  // 58
    Some("arcanine"),   // 59
    Some("poliwag"),    // 60
    Some("poliwhirl"),  // 61
    Some("poliwrath"),  // 62
    Some("abra"),       // 63
    Some("kadabra"),    // 64
    Some("alakazam"),   // 65
    Some("machop"),     // 66
    Some("machoke"),    // 67
    Some("machamp"),    // 68
    Some("bellsprout"), // 69
    Some("weepinbell"), // 70
    Some("victreebel"), // 71
    Some("tentacool"),  // 72
    Some("tentacruel"), // 73
    Some("geodude"),    // 74
    Some("graveler"),   // 75
    Some("golem"),      // 76
    Some("ponyta"),     // 77
    Some("rapidash"),   // 78
    Some("slowpoke"),   // 79
    Some("slowbro"),    // 80
    Some("magnemite"),  // 81
    Some("magneton"),   // 82
    Some("farfetchd"),  // 83
    Some("doduo"),      // 84
    Some("dodrio"),     // 85
    Some("seel"),       // 86
    Some("dewgong"),    // 87
    Some("grimer"),     // 88
    Some("muk"),        // 89
    Some("shellder"),   // 90
    Some("cloyster"),   // 91
    Some("gastly"),     // 92
    Some("haunter"),    // 93
    Some("gengar"),     // 94
    Some("onix"),       // 95
    Some("drowzee"),    // 96
    Some("hypno"),      // 97
    Some("krabby"),     // 98
    Some("kingler"),    // 99
    Some("voltorb"),    // 100
    Some("electrode"),  // 101
    Some("exeggcute"),  // 102
    Some("exeggutor"),  // 103
    Some("cubone"),     // 104
    Some("marowak"),    // 105
    Some("hitmonlee"),  // 106
    Some("hitmonchan"), // 107
    Some("lickitung"),  // 108
    Some("koffing"),    // 109
    Some("weezing"),    // 110
    Some("rhyhorn"),    // 111
    Some("rhydon"),     // 112
    Some("chansey"),    // 113
    Some("tangela"),    // 114
    Some("kangaskhan"), // 115
    Some("horsea"),     // 116
    Some("seadra"),     // 117
    Some("goldeen"),    // 118
    Some("seaking"),    // 119
    Some("staryu"),     // 120
    Some("starmie"),    // 121
    Some("mrmime"),     // 122
    Some("scyther"),    // 123
    Some("jynx"),       // 124
    Some("electabuzz"), // 125
    Some("magmar"),     // 126
    Some("pinsir"),     // 127
    Some("tauros"),     // 128
    Some("magikarp"),   // 129
    Some("gyarados"),   // 130
    Some("lapras"),     // 131
    Some("ditto"),      // 132
    Some("eevee"),      // 133
    Some("vaporeon"),   // 134
    Some("jolteon"),    // 135
    Some("flareon"),    // 136
    Some("porygon"),    // 137
    Some("omanyte"),    // 138
    Some("omastar"),    // 139
    Some("kabuto"),     // 140
    Some("kabutops"),   // 141
    Some("aerodactyl"), // 142
    Some("snorlax"),    // 143
    Some("articuno"),   // 144
    Some("zapdos"),     // 145
    Some("moltres"),    // 146
    Some("dratini"),    // 147
    Some("dragonair"),  // 148
    Some("dragonite"),  // 149
    Some("mewtwo"),     // 150
    Some("mew"),        // 151
    Some("chikorita"),  // 152
    Some("bayleef"),    // 153
    Some("meganium"),   // 154
    Some("cyndaquil"),  // 155
    Some("quilava"),    // 156
    Some("typhlosion"), // 157
    Some("totodile"),   // 158
    Some("croconaw"),   // 159
    Some("feraligatr"), // 160
    Some("sentret"),    // 161
    Some("furret"),     // 162
    Some("hoothoot"),   // 163
    Some("noctowl"),    // 164
    Some("ledyba"),     // 165
    Some("ledian"),     // 166
    Some("spinarak"),   // 167
    Some("ariados"),    // 168
    Some("crobat"),     // 169
    Some("chinchou"),   // 170
    Some("lanturn"),    // 171
    Some("pichu"),      // 172
    Some("cleffa"),     // 173
    Some("igglybuff"),  // 174
    Some("togepi"),     // 175
    Some("togetic"),    // 176
    Some("natu"),       // 177
    Some("xatu"),       // 178
    Some("mareep"),     // 179
    Some("flaaffy"),    // 180
    Some("ampharos"),   // 181
    Some("bellossom"),  // 182
    Some("marill"),     // 183
    Some("azumarill"),  // 184
    Some("sudowoodo"),  // 185
    Some("politoed"),   // 186
    Some("hoppip"),     // 187
    Some("skiploom"),   // 188
    Some("jumpluff"),   // 189
    Some("aipom"),      // 190
    Some("sunkern"),    // 191
    Some("sunflora"),   // 192
    Some("yanma"),      // 193
    Some("wooper"),     // 194
    Some("quagsire"),   // 195
    Some("espeon"),     // 196
    Some("umbreon"),    // 197
    Some("murkrow"),    // 198
    Some("slowking"),   // 199
    Some("misdreavus"), // 200
    Some("unown"),      // 201
    Some("wobbuffet"),  // 202
    Some("girafarig"),  // 203
    Some("pineco"),     // 204
    Some("forretress"), // 205
    Some("dunsparce"),  // 206
    Some("gligar"),     // 207
    Some("steelix"),    // 208
    Some("snubbull"),   // 209
    Some("granbull"),   // 210
    Some("qwilfish"),   // 211
    Some("scizor"),     // 212
    Some("shuckle"),    // 213
    Some("heracross"),  // 214
    Some("sneasel"),    // 215
    Some("teddiursa"),  // 216
    Some("ursaring"),   // 217
    Some("slugma"),     // 218
    Some("magcargo"),   // 219
    Some("swinub"),     // 220
    Some("piloswine"),  // 221
    Some("corsola"),    // 222
    Some("remoraid"),   // 223
    Some("octillery"),  // 224
    Some("delibird"),   // 225
    Some("mantine"),    // 226
    Some("skarmory"),   // 227
    Some("houndour"),   // 228
    Some("houndoom"),   // 229
    Some("kingdra"),    // 230
    Some("phanpy"),     // 231
    Some("donphan"),    // 232
    Some("porygon2"),   // 233
    Some("stantler"),   // 234
    Some("smeargle"),   // 235
    Some("tyrogue"),    // 236
    Some("hitmontop"),  // 237
    Some("smoochum"),   // 238
    Some("elekid"),     // 239
    Some("magby"),      // 240
    Some("miltank"),    // 241
    Some("blissey"),    // 242
    Some("raikou"),     // 243
    Some("entei"),      // 244
    Some("suicune"),    // 245
    Some("larvitar"),   // 246
    Some("pupitar"),    // 247
    Some("tyranitar"),  // 248
    Some("lugia"),      // 249
    Some("hooh"),       // 250
    Some("celebi"),     // 251
    Some("treecko"),    // 252
    Some("grovyle"),    // 253
    Some("sceptile"),   // 254
    Some("torchic"),    // 255
    Some("combusken"),  // 256
    Some("blaziken"),   // 257
    Some("mudkip"),     // 258
    Some("marshtomp"),  // 259
    Some("swampert"),   // 260
    Some("poochyena"),  // 261
    Some("mightyena"),  // 262
    Some("zigzagoon"),  // 263
    Some("linoone"),    // 264
    Some("wurmple"),    // 265
    Some("silcoon"),    // 266
    Some("beautifly"),  // 267
    Some("cascoon"),    // 268
    Some("dustox"),     // 269
    Some("lotad"),      // 270
    Some("lombre"),     // 271
    Some("ludicolo"),   // 272
    Some("seedot"),     // 273
    Some("nuzleaf"),    // 274
    Some("shiftry"),    // 275
    Some("taillow"),    // 276
    Some("swellow"),    // 277
    Some("wingull"),    // 278
    Some("pelipper"),   // 279
    Some("ralts"),      // 280
    Some("kirlia"),     // 281
    Some("gardevoir"),  // 282
    Some("surskit"),    // 283
    Some("masquerain"), // 284
    Some("shroomish"),  // 285
    Some("breloom"),    // 286
    Some("slakoth"),    // 287
    Some("vigoroth"),   // 288
    Some("slaking"),    // 289
    Some("nincada"),    // 290
    Some("ninjask"),    // 291
    Some("shedinja"),   // 292
    Some("whismur"),    // 293
    Some("loudred"),    // 294
    Some("exploud"),    // 295
    Some("makuhita"),   // 296
    Some("hariyama"),   // 297
    Some("azurill"),    // 298
    Some("nosepass"),   // 299
    Some("skitty"),     // 300
    Some("delcatty"),   // 301
    Some("sableye"),    // 302
    Some("mawile"),     // 303
    Some("aron"),       // 304
    Some("lairon"),     // 305
    Some("aggron"),     // 306
    Some("meditite"),   // 307
    Some("medicham"),   // 308
    Some("electrike"),  // 309
    Some("manectric"),  // 310
    Some("plusle"),     // 311
    Some("minun"),      // 312
    Some("volbeat"),    // 313
    Some("illumise"),   // 314
    Some("roselia"),    // 315
    Some("gulpin"),     // 316
    Some("swalot"),     // 317
    Some("carvanha"),   // 318
    Some("sharpedo"),   // 319
    Some("wailmer"),    // 320
    Some("wailord"),    // 321
    Some("numel"),      // 322
    Some("camerupt"),   // 323
    Some("torkoal"),    // 324
    Some("spoink"),     // 325
    Some("grumpig"),    // 326
    Some("spinda"),     // 327
    Some("trapinch"),   // 328
    Some("vibrava"),    // 329
    Some("flygon"),     // 330
    Some("cacnea"),     // 331
    Some("cacturne"),   // 332
    Some("swablu"),     // 333
    Some("altaria"),    // 334
    Some("zangoose"),   // 335
    Some("seviper"),    // 336
    Some("lunatone"),   // 337
    Some("solrock"),    // 338
    Some("barboach"),   // 339
    Some("whiscash"),   // 340
    Some("corphish"),   // 341
    Some("crawdaunt"),  // 342
    Some("baltoy"),     // 343
    Some("claydol"),    // 344
    Some("lileep"),     // 345
    Some("cradily"),    // 346
    Some("anorith"),    // 347
    Some("armaldo"),    // 348
    Some("feebas"),     // 349
    Some("milotic"),    // 350
    Some("castform"),   // 351
    Some("kecleon"),    // 352
    Some("shuppet"),    // 353
    Some("banette"),    // 354
    Some("duskull"),    // 355
    Some("dusclops"),   // 356
    Some("tropius"),    // 357
    Some("chimecho"),   // 358
    Some("absol"),      // 359
    Some("wynaut"),     // 360
    Some("snorunt"),    // 361
    Some("glalie"),     // 362
    Some("spheal"),     // 363
    Some("sealeo"),     // 364
    Some("walrein"),    // 365
    Some("clamperl"),   // 366
    Some("huntail"),    // 367
    Some("gorebyss"),   // 368
    Some("relicanth"),  // 369
    Some("luvdisc"),    // 370
    Some("bagon"),      // 371
    Some("shelgon"),    // 372
    Some("salamence"),  // 373
    Some("beldum"),     // 374
    Some("metang"),     // 375
    Some("metagross"),  // 376
    Some("regirock"),   // 377
    Some("regice"),     // 378
    Some("registeel"),  // 379
    Some("latias"),     // 380
    Some("latios"),     // 381
    Some("kyogre"),     // 382
    Some("groudon"),    // 383
    Some("rayquaza"),   // 384
    Some("jirachi"),    // 385
    Some("deoxys"),     // 386
    Some("turtwig"),    // 387
    Some("grotle"),     // 388
    Some("torterra"),   // 389
    Some("chimchar"),   // 390
    Some("monferno"),   // 391
    Some("infernape"),  // 392
    Some("piplup"),     // 393
    Some("prinplup"),   // 394
    Some("empoleon"),   // 395
    Some("starly"),     // 396
    Some("staravia"),   // 397
    Some("staraptor"),  // 398
    Some("bidoof"),     // 399
    Some("bibarel"),    // 400
    Some("kricketot"),  // 401
    Some("kricketune"), // 402
    Some("shinx"),      // 403
    Some("luxio"),      // 404
    Some("luxray"),     // 405
    Some("budew"),      // 406
    Some("roserade"),   // 407
    Some("cranidos"),   // 408
    Some("rampardos"),  // 409
    Some("shieldon"),   // 410
    Some("bastiodon"),  // 411
    Some("burmy"),      // 412
    Some("wormadam"),   // 413
    Some("mothim"),     // 414
    Some("combee"),     // 415
    Some("vespiquen"),  // 416
    Some("pachirisu"),  // 417
    Some("buizel"),     // 418
    Some("floatzel"),   // 419
    Some("cherubi"),    // 420
    Some("cherrim"),    // 421
    Some("shellos"),    // 422
    Some("gastrodon"),  // 423
    Some("ambipom"),    // 424
    Some("drifloon"),   // 425
    Some("drifblim"),   // 426
    Some("buneary"),    // 427
    Some("lopunny"),    // 428
    Some("mismagius"),  // 429
    Some("honchkrow"),  // 430
    Some("glameow"),    // 431
    Some("purugly"),    // 432
    Some("chingling"),  // 433
    Some("stunky"),     // 434
    Some("skuntank"),   // 435
    Some("bronzor"),    // 436
    Some("bronzong"),   // 437
    Some("bonsly"),     // 438
    Some("mimejr"),     // 439
    Some("happiny"),    // 440
    Some("chatot"),     // 441
    Some("spiritomb"),  // 442
    Some("gible"),      // 443
    Some("gabite"),     // 444
    Some("garchomp"),   // 445
    Some("munchlax"),   // 446
    Some("riolu"),      // 447
    Some("lucario"),    // 448
    Some("hippopotas"), // 449
    Some("hippowdon"),  // 450
    Some("skorupi"),    // 451
    Some("drapion"),    // 452
    Some("croagunk"),   // 453
    Some("toxicroak"),  // 454
    Some("carnivine"),  // 455
    Some("finneon"),    // 456
    Some("lumineon"),   // 457
    Some("mantyke"),    // 458
    Some("snover"),     // 459
    Some("abomasnow"),  // 460
    Some("weavile"),    // 461
    Some("magnezone"),  // 462
    Some("lickilicky"), // 463
    Some("rhyperior"),  // 464
    Some("tangrowth"),  // 465
    Some("electivire"), // 466
    Some("magmortar"),  // 467
    Some("togekiss"),   // 468
    Some("yanmega"),    // 469
    Some("leafeon"),    // 470
    Some("glaceon"),    // 471
    Some("gliscor"),    // 472
    Some("mamoswine"),  // 473
    Some("porygonz"),   // 474
    Some("gallade"),    // 475
    Some("probopass"),  // 476
    Some("dusknoir"),   // 477
    Some("froslass"),   // 478
    Some("rotom"),      // 479
    Some("uxie"),       // 480
    Some("mesprit"),    // 481
    Some("azelf"),      // 482
    Some("dialga"),     // 483
    Some("palkia"),     // 484
    Some("heatran"),    // 485
    Some("regigigas"),  // 486
    Some("giratina"),   // 487
    Some("cresselia"),  // 488
    Some("phione"),     // 489
    Some("manaphy"),    // 490
    Some("darkrai"),    // 491
    Some("shaymin"),    // 492
    Some("arceus"),     // 493
];
